import type { ProductListItem, Brand, Banner } from '@/types/api';

export const MOCK_PRODUCTS: ProductListItem[] = [
  {
    id: 901,
    name: 'Naturehike Cloud Up 2 Kisilik Cadir',
    slug: 'naturehike-cloud-up-2-kisilik-cadir',
    price: 4299,
    comparePrice: 5499,
    stockQuantity: 15,
    stockStatus: 'in_stock',
    isActive: true,
    isFeatured: true,
    isBestseller: false,
    isNew: false,
    mainImage: null,
    brandName: 'Naturehike',
    categoryName: 'Cadirlar',
  },
  {
    id: 902,
    name: 'Deuter Orbit -5° Uyku Tulumu',
    slug: 'deuter-orbit-minus-5-uyku-tulumu',
    price: 3150,
    comparePrice: null,
    stockQuantity: 22,
    stockStatus: 'in_stock',
    isActive: true,
    isFeatured: true,
    isBestseller: false,
    isNew: true,
    mainImage: null,
    brandName: 'Deuter',
    categoryName: 'Uyku Tulumlari',
  },
  {
    id: 903,
    name: 'Osprey Atmos AG 65L Sirt Cantasi',
    slug: 'osprey-atmos-ag-65l-sirt-cantasi',
    price: 8750,
    comparePrice: 9900,
    stockQuantity: 8,
    stockStatus: 'in_stock',
    isActive: true,
    isFeatured: true,
    isBestseller: false,
    isNew: false,
    mainImage: null,
    brandName: 'Osprey',
    categoryName: 'Sirt Cantalari',
  },
  {
    id: 904,
    name: 'MSR PocketRocket 2 Kamp Ocagi',
    slug: 'msr-pocketrocket-2-kamp-ocagi',
    price: 1899,
    comparePrice: null,
    stockQuantity: 30,
    stockStatus: 'in_stock',
    isActive: true,
    isFeatured: false,
    isBestseller: false,
    isNew: true,
    mainImage: null,
    brandName: 'MSR',
    categoryName: 'Kamp Ocaklari',
  },
  {
    id: 905,
    name: 'Nalgene Wide Mouth 1L Matara',
    slug: 'nalgene-wide-mouth-1l-matara',
    price: 450,
    comparePrice: 599,
    stockQuantity: 50,
    stockStatus: 'in_stock',
    isActive: true,
    isFeatured: false,
    isBestseller: false,
    isNew: false,
    mainImage: null,
    brandName: 'Nalgene',
    categoryName: 'Mataralar',
  },
  {
    id: 906,
    name: 'Petzl Actik Core Bas Feneri',
    slug: 'petzl-actik-core-bas-feneri',
    price: 1350,
    comparePrice: null,
    stockQuantity: 18,
    stockStatus: 'in_stock',
    isActive: true,
    isFeatured: true,
    isBestseller: false,
    isNew: true,
    mainImage: null,
    brandName: 'Petzl',
    categoryName: 'Aydinlatma',
  },
  {
    id: 907,
    name: 'Black Diamond Trail Trekking Baton (Cift)',
    slug: 'black-diamond-trail-trekking-baton',
    price: 2100,
    comparePrice: 2500,
    stockQuantity: 12,
    stockStatus: 'in_stock',
    isActive: true,
    isFeatured: false,
    isBestseller: false,
    isNew: false,
    mainImage: null,
    brandName: 'Black Diamond',
    categoryName: 'Trekking',
  },
  {
    id: 908,
    name: 'Helinox Chair One Kamp Sandalyesi',
    slug: 'helinox-chair-one-kamp-sandalyesi',
    price: 3600,
    comparePrice: null,
    stockQuantity: 10,
    stockStatus: 'in_stock',
    isActive: true,
    isFeatured: true,
    isBestseller: false,
    isNew: false,
    mainImage: null,
    brandName: 'Helinox',
    categoryName: 'Kamp Mobilyasi',
  },
  {
    id: 909,
    name: 'Victorinox Huntsman Caki',
    slug: 'victorinox-huntsman-caki',
    price: 1750,
    comparePrice: 1990,
    stockQuantity: 25,
    stockStatus: 'in_stock',
    isActive: true,
    isFeatured: false,
    isBestseller: false,
    isNew: false,
    mainImage: null,
    brandName: 'Victorinox',
    categoryName: 'Bicak & Caki',
  },
  {
    id: 910,
    name: 'Salomon X Ultra 4 GTX Outdoor Bot',
    slug: 'salomon-x-ultra-4-gtx-outdoor-bot',
    price: 5490,
    comparePrice: 6200,
    stockQuantity: 6,
    stockStatus: 'in_stock',
    isActive: true,
    isFeatured: true,
    isBestseller: false,
    isNew: true,
    mainImage: null,
    brandName: 'Salomon',
    categoryName: 'Ayakkabi',
  },
  {
    id: 911,
    name: 'Sea to Summit Ultralight Mat',
    slug: 'sea-to-summit-ultralight-mat',
    price: 2890,
    comparePrice: 3400,
    stockQuantity: 14,
    stockStatus: 'in_stock',
    isActive: true,
    isFeatured: true,
    isBestseller: false,
    isNew: false,
    mainImage: null,
    brandName: 'Sea to Summit',
    categoryName: 'Kamp Matlari',
  },
  {
    id: 912,
    name: 'Jetboil Flash Pisirme Sistemi',
    slug: 'jetboil-flash-pisirme-sistemi',
    price: 3750,
    comparePrice: null,
    stockQuantity: 20,
    stockStatus: 'in_stock',
    isActive: true,
    isFeatured: true,
    isBestseller: false,
    isNew: true,
    mainImage: null,
    brandName: 'Jetboil',
    categoryName: 'Kamp Ocaklari',
  },
  {
    id: 913,
    name: 'Deuter Aircontact Lite 50+10',
    slug: 'deuter-aircontact-lite-50-10',
    price: 6200,
    comparePrice: 7100,
    stockQuantity: 9,
    stockStatus: 'in_stock',
    isActive: true,
    isFeatured: true,
    isBestseller: false,
    isNew: false,
    mainImage: null,
    brandName: 'Deuter',
    categoryName: 'Sirt Cantalari',
  },
  {
    id: 914,
    name: 'MSR Hubba Hubba NX 2 Cadir',
    slug: 'msr-hubba-hubba-nx-2-cadir',
    price: 12500,
    comparePrice: 14000,
    stockQuantity: 5,
    stockStatus: 'in_stock',
    isActive: true,
    isFeatured: true,
    isBestseller: false,
    isNew: false,
    mainImage: null,
    brandName: 'MSR',
    categoryName: 'Cadirlar',
  },
  {
    id: 915,
    name: 'Petzl Tikka 300 Lumen Bas Feneri',
    slug: 'petzl-tikka-300-lumen-bas-feneri',
    price: 890,
    comparePrice: null,
    stockQuantity: 35,
    stockStatus: 'in_stock',
    isActive: true,
    isFeatured: true,
    isBestseller: false,
    isNew: false,
    mainImage: null,
    brandName: 'Petzl',
    categoryName: 'Aydinlatma',
  },
  {
    id: 916,
    name: 'Black Diamond Spot 400 Bas Feneri',
    slug: 'black-diamond-spot-400-bas-feneri',
    price: 1150,
    comparePrice: 1350,
    stockQuantity: 28,
    stockStatus: 'in_stock',
    isActive: true,
    isFeatured: true,
    isBestseller: false,
    isNew: true,
    mainImage: null,
    brandName: 'Black Diamond',
    categoryName: 'Aydinlatma',
  },
  {
    id: 917,
    name: 'Naturehike Mongar 2 Kisilik Cadir',
    slug: 'naturehike-mongar-2-kisilik-cadir',
    price: 3899,
    comparePrice: 4500,
    stockQuantity: 11,
    stockStatus: 'in_stock',
    isActive: true,
    isFeatured: true,
    isBestseller: false,
    isNew: false,
    mainImage: null,
    brandName: 'Naturehike',
    categoryName: 'Cadirlar',
  },
  {
    id: 918,
    name: 'Osprey Talon 22 Gunluk Canta',
    slug: 'osprey-talon-22-gunluk-canta',
    price: 3200,
    comparePrice: null,
    stockQuantity: 16,
    stockStatus: 'in_stock',
    isActive: true,
    isFeatured: true,
    isBestseller: false,
    isNew: false,
    mainImage: null,
    brandName: 'Osprey',
    categoryName: 'Sirt Cantalari',
  },
  {
    id: 919,
    name: 'Sea to Summit Aeros Premium Yastik',
    slug: 'sea-to-summit-aeros-premium-yastik',
    price: 680,
    comparePrice: 790,
    stockQuantity: 40,
    stockStatus: 'in_stock',
    isActive: true,
    isFeatured: true,
    isBestseller: false,
    isNew: true,
    mainImage: null,
    brandName: 'Sea to Summit',
    categoryName: 'Uyku Ekipmanlari',
  },
  {
    id: 920,
    name: 'Helinox Table One Hard Top',
    slug: 'helinox-table-one-hard-top',
    price: 4200,
    comparePrice: 4800,
    stockQuantity: 7,
    stockStatus: 'in_stock',
    isActive: true,
    isFeatured: true,
    isBestseller: false,
    isNew: false,
    mainImage: null,
    brandName: 'Helinox',
    categoryName: 'Kamp Mobilyasi',
  },
];

export const MOCK_BANNERS: Banner[] = [
  {
    id: 901,
    title: 'Yaz Kampanyasi',
    subtitle: 'Yeni Sezon',
    imageUrl: '/placeholder-banner.jpg',
    mobileImageUrl: null,
    linkUrl: '/tum-urunler',
    buttonText: 'Keşfet',
    titleColor: '#FFFFFF',
    subtitleColor: '#FFFFFF',
    buttonColor: '#FFFFFF',
    position: 'hero',
    sortOrder: 1,
  },
];

export const MOCK_BRANDS: Brand[] = [
  { id: 901, name: 'Naturehike', slug: 'naturehike', logoUrl: null, isActive: true, isFeatured: true },
  { id: 902, name: 'Deuter', slug: 'deuter', logoUrl: null, isActive: true, isFeatured: true },
  { id: 903, name: 'MSR', slug: 'msr', logoUrl: null, isActive: true, isFeatured: true },
  { id: 904, name: 'Petzl', slug: 'petzl', logoUrl: null, isActive: true, isFeatured: true },
  { id: 905, name: 'Black Diamond', slug: 'black-diamond', logoUrl: null, isActive: true, isFeatured: true },
  { id: 906, name: 'Osprey', slug: 'osprey', logoUrl: null, isActive: true, isFeatured: true },
  { id: 907, name: 'Sea to Summit', slug: 'sea-to-summit', logoUrl: null, isActive: true, isFeatured: true },
  { id: 908, name: 'Jetboil', slug: 'jetboil', logoUrl: null, isActive: true, isFeatured: true },
];
